### ISSUE TITLE
[asm_software] Use disk_au_size of 1 for OCR diskgroup in RAC

### ISSUE THREAD

**Issue by remyvb** [enterprisemodules/ora_profile#20]
For performance reasons it's probably better to have 1MB disk_au_size for the OCR diskgroup in a RAC installation.

**Comment by hajee** [comment]
Moved to [here](https://app.clubhouse.io/enterprise-modules-bv/story/278/asm-software-use-disk-au-size-of-1-for-ocr-diskgroup-in-rac)
