### ISSUE TITLE
[asm/db_software] Consider/Think about how to specify cluster_new_node_vip

### ISSUE THREAD

**Issue by remyvb** [enterprisemodules/ora_profile#25]
In a RAC installation on the non-master_node we rely on the vip to be called ${hostname}-vip, which isn't always the case. Should we add functionality to specify the vip-name or continue to rely on the best practice we have implemented.

**Comment by hajee** [comment]
Moved to [here](https://app.clubhouse.io/enterprise-modules-bv/story/276/asm-db-software-consider-think-about-how-to-specify-cluster-new-node-vip)
